# ./src/app.yaml
# When deploying to Google App Engine with command:
# gcloud app deploy
# This file will be parsed as a configuration file and is mandatory
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: server.server.app

libraries:
- name: ssl
  version: latest

skip_files:
- node_modules/
- static/node_modules/
- venv/
