# ./src/app.yaml
# When deploying to Google App Engine with command:
# gcloud app deploy
# This file will be parsed as a configuration file and is mandatory
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/resources/favicon.ico
  upload: static/resources/favicon\.ico
- url: /.*
  script: server.server.app
  secure: always

libraries:
- name: ssl
  version: latest

skip_files:
- js/
- static/js/
- node_modules/
- static/node_modules/
- venv/
